version: "3"
services:
  mysql:
    image: mysql:5.7
    env_file:
      - env
    command: mysqld

  magento:
    image: alexcheng/magento2
    env_file:
      - env
    ports:
      - "8080:80"
    links:
      - mysql
